-- MySQL Script generated by MySQL Workbench
-- Tue Aug 13 16:09:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`revista_cientifica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`revista_cientifica` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `volume` INT NULL,
  `numero` INT NULL,
  `editora` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artigo` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `resumo` MEDIUMTEXT NULL,
  `area` VARCHAR(45) NULL,
  `paginas` INT NULL,
  `ano` VARCHAR(4) NULL,
  `revista_cientifica_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_artigo_revista_cientifica_idx` (`revista_cientifica_id` ASC) VISIBLE,
  CONSTRAINT `fk_artigo_revista_cientifica`
    FOREIGN KEY (`revista_cientifica_id`)
    REFERENCES `mydb`.`revista_cientifica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autor` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `local_trabalho` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artigo_autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artigo_autor` (
  `artigo_id` INT NOT NULL,
  `autor_id` INT NOT NULL,
  PRIMARY KEY (`artigo_id`, `autor_id`),
  INDEX `fk_artigo_has_autor_autor1_idx` (`autor_id` ASC) VISIBLE,
  INDEX `fk_artigo_has_autor_artigo1_idx` (`artigo_id` ASC) VISIBLE,
  CONSTRAINT `fk_artigo_has_autor_artigo1`
    FOREIGN KEY (`artigo_id`)
    REFERENCES `mydb`.`artigo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artigo_has_autor_autor1`
    FOREIGN KEY (`autor_id`)
    REFERENCES `mydb`.`autor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
