-- MySQL Script generated by MySQL Workbench
-- Sun Aug 11 21:18:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idcliente` INT NOT NULL,
  `endereco` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente_fisico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente_fisico` (
  `idcliente` INT NOT NULL,
  `cpf` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_fisico_cliente1_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_fisico_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente_juridico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente_juridico` (
  `idcliente` INT NOT NULL,
  `cnpj` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_juridico_cliente_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_juridico_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`editora` (
  `ideditora` INT NOT NULL,
  `endereco` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `gerente` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`ideditora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livro` (
  `idlivro` INT NOT NULL,
  `autor` VARCHAR(45) NULL,
  `assunto` VARCHAR(45) NULL,
  `editora` VARCHAR(45) NULL,
  `isbn` VARCHAR(45) NULL,
  `estoque` INT NULL,
  `editora_ideditora` INT NOT NULL,
  PRIMARY KEY (`idlivro`, `editora_ideditora`),
  INDEX `fk_livro_editora1_idx` (`editora_ideditora` ASC) VISIBLE,
  CONSTRAINT `fk_livro_editora1`
    FOREIGN KEY (`editora_ideditora`)
    REFERENCES `mydb`.`editora` (`ideditora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historico_compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historico_compras` (
  `idcliente` INT NOT NULL,
  `idlivro` INT NOT NULL,
  PRIMARY KEY (`idcliente`, `idlivro`),
  INDEX `fk_cliente_has_livro_livro1_idx` (`idlivro` ASC) VISIBLE,
  INDEX `fk_cliente_has_livro_cliente1_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_livro_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_livro_livro1`
    FOREIGN KEY (`idlivro`)
    REFERENCES `mydb`.`livro` (`idlivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
