-- MySQL Script generated by MySQL Workbench
-- Tue Aug 13 09:03:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vendedor` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `vendedor_gerenciador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vendedor_vendedor_idx` (`vendedor_gerenciador_id` ASC) VISIBLE,
  CONSTRAINT `fk_vendedor_vendedor`
    FOREIGN KEY (`vendedor_gerenciador_id`)
    REFERENCES `mydb`.`vendedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `vendedor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_vendedor1_idx` (`vendedor_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_vendedor1`
    FOREIGN KEY (`vendedor_id`)
    REFERENCES `mydb`.`vendedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `data` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedido_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `mydb`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item_estoque` (
  `id` INT NOT NULL,
  `preco` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido_item` (
  `pedido_id` INT NOT NULL,
  `item_estoque_id` INT NOT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`pedido_id`, `item_estoque_id`),
  INDEX `fk_pedido_has_item_estoque_item_estoque1_idx` (`item_estoque_id` ASC) VISIBLE,
  INDEX `fk_pedido_has_item_estoque_pedido1_idx` (`pedido_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_item_estoque_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `mydb`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_item_estoque_item_estoque1`
    FOREIGN KEY (`item_estoque_id`)
    REFERENCES `mydb`.`item_estoque` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`peca` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item_peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item_peca` (
  `item_estoque_id` INT NOT NULL,
  `peca_id` INT NOT NULL,
  `quantidade_peca` INT NULL,
  PRIMARY KEY (`item_estoque_id`, `peca_id`),
  INDEX `fk_item_estoque_has_peca_peca1_idx` (`peca_id` ASC) VISIBLE,
  INDEX `fk_item_estoque_has_peca_item_estoque1_idx` (`item_estoque_id` ASC) VISIBLE,
  CONSTRAINT `fk_item_estoque_has_peca_item_estoque1`
    FOREIGN KEY (`item_estoque_id`)
    REFERENCES `mydb`.`item_estoque` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_estoque_has_peca_peca1`
    FOREIGN KEY (`peca_id`)
    REFERENCES `mydb`.`peca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `setor` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`peca_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`peca_funcionario` (
  `peca_id` INT NOT NULL,
  `funcionario_id` INT NOT NULL,
  PRIMARY KEY (`peca_id`, `funcionario_id`),
  INDEX `fk_peca_has_funcionario_funcionario1_idx` (`funcionario_id` ASC) VISIBLE,
  INDEX `fk_peca_has_funcionario_peca1_idx` (`peca_id` ASC) VISIBLE,
  CONSTRAINT `fk_peca_has_funcionario_peca1`
    FOREIGN KEY (`peca_id`)
    REFERENCES `mydb`.`peca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peca_has_funcionario_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `mydb`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario_item` (
  `funcionario_id` INT NOT NULL,
  `item_estoque_id` INT NOT NULL,
  `tempo_medio_montagem` INT NULL,
  PRIMARY KEY (`funcionario_id`, `item_estoque_id`),
  INDEX `fk_funcionario_has_item_estoque_item_estoque1_idx` (`item_estoque_id` ASC) VISIBLE,
  INDEX `fk_funcionario_has_item_estoque_funcionario1_idx` (`funcionario_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_has_item_estoque_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `mydb`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_has_item_estoque_item_estoque1`
    FOREIGN KEY (`item_estoque_id`)
    REFERENCES `mydb`.`item_estoque` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor` (
  `id` INT NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `qualidade` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor_peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor_peca` (
  `fornecedor_id` INT NOT NULL,
  `peca_id` INT NOT NULL,
  PRIMARY KEY (`fornecedor_id`, `peca_id`),
  INDEX `fk_fornecedor_has_peca_peca1_idx` (`peca_id` ASC) VISIBLE,
  INDEX `fk_fornecedor_has_peca_fornecedor1_idx` (`fornecedor_id` ASC) VISIBLE,
  CONSTRAINT `fk_fornecedor_has_peca_fornecedor1`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `mydb`.`fornecedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fornecedor_has_peca_peca1`
    FOREIGN KEY (`peca_id`)
    REFERENCES `mydb`.`peca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
