-- MySQL Script generated by MySQL Workbench
-- Sat Sep 21 13:51:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema site1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema site1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `site1` DEFAULT CHARACTER SET utf8 ;
USE `site1` ;

-- -----------------------------------------------------
-- Table `site1`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site1`.`usuario` (
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `nascimento` DATE NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
