-- MySQL Script generated by MySQL Workbench
-- Thu Sep 26 19:25:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema a2023951431@teiacoltec.org
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema a2023951431@teiacoltec.org
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `a2023951431@teiacoltec.org` DEFAULT CHARACTER SET utf8 ;
USE `a2023951431@teiacoltec.org` ;

-- -----------------------------------------------------
-- Table `a2023951431@teiacoltec.org`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a2023951431@teiacoltec.org`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nascimento` VARCHAR(45) NOT NULL,
  `acesso` ENUM("usuario", "gerente", "admin") NOT NULL,
  `status` ENUM("ativo", "inativo") NOT NULL DEFAULT 'ativo',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
