-- MySQL Script generated by MySQL Workbench
-- Wed Oct 23 19:02:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema a2023951431@teiacoltec.org
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema a2023951431@teiacoltec.org
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `a2023951431@teiacoltec.org` DEFAULT CHARACTER SET utf8 ;
USE `a2023951431@teiacoltec.org` ;

-- -----------------------------------------------------
-- Table `a2023951431@teiacoltec.org`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a2023951431@teiacoltec.org`.`login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a2023951431@teiacoltec.org`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a2023951431@teiacoltec.org`.`usuario` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `genero` ENUM("masculino", "feminino") NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `acesso` ENUM("cliente", "funcionario", "admin") NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuario_login`
    FOREIGN KEY (`id`)
    REFERENCES `a2023951431@teiacoltec.org`.`login` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a2023951431@teiacoltec.org`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a2023951431@teiacoltec.org`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `salario` DOUBLE NOT NULL,
  `setor` ENUM("logistica", "TI", "marketing") NOT NULL,
  INDEX `fk_funcionario_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `a2023951431@teiacoltec.org`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a2023951431@teiacoltec.org`.`gastos_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a2023951431@teiacoltec.org`.`gastos_funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_funcionario` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `valor` DOUBLE NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  INDEX `fk_gastos_funcionario_funcionario1_idx` (`id_funcionario` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_gastos_funcionario_funcionario1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `a2023951431@teiacoltec.org`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a2023951431@teiacoltec.org`.`historico_logins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a2023951431@teiacoltec.org`.`historico_logins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_login` INT NOT NULL,
  `data` DATETIME NOT NULL,
  INDEX `fk_historico_logins_login1_idx` (`id_login` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_historico_logins_login1`
    FOREIGN KEY (`id_login`)
    REFERENCES `a2023951431@teiacoltec.org`.`login` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a2023951431@teiacoltec.org`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a2023951431@teiacoltec.org`.`pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `preco_produtos` DOUBLE NOT NULL,
  `preco_frete` DOUBLE NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `status` ENUM("pagamento nao efetuado", "pagamento efetuado", "em transporte", "recebido", "cancelado", "devolvido") NOT NULL,
  `forma_pagamento` ENUM("pix", "boleto", "cartao") NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedido_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `a2023951431@teiacoltec.org`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a2023951431@teiacoltec.org`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a2023951431@teiacoltec.org`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `preco_real` DOUBLE NOT NULL,
  `preco_venda` DOUBLE NOT NULL,
  `estoque` INT NOT NULL,
  `descricao` VARCHAR(100) NULL,
  `tipo` ENUM("material escolar", "livro") NOT NULL,
  `imagem` BLOB NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a2023951431@teiacoltec.org`.`pedido_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a2023951431@teiacoltec.org`.`pedido_produto` (
  `id_pedido` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `quantidade_produto` DOUBLE NOT NULL,
  PRIMARY KEY (`id_pedido`, `id_produto`),
  INDEX `fk_pedido_has_produto_produto1_idx` (`id_produto` ASC) VISIBLE,
  INDEX `fk_pedido_has_produto_pedido1_idx` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_produto_pedido1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `a2023951431@teiacoltec.org`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_produto_produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `a2023951431@teiacoltec.org`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a2023951431@teiacoltec.org`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a2023951431@teiacoltec.org`.`livro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_produto` INT NOT NULL,
  `genero` VARCHAR(50) NOT NULL,
  `num_paginas` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_livro_produto1_idx` (`id_produto` ASC) VISIBLE,
  UNIQUE INDEX `id_produto_UNIQUE` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_livro_produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `a2023951431@teiacoltec.org`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
