-- MySQL Script generated by MySQL Workbench
-- Mon Aug 12 20:16:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hospital` (
  `cnpj` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`enfermeira_chefe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`enfermeira_chefe` (
  `numero_registro` INT NOT NULL,
  PRIMARY KEY (`numero_registro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`enfermeira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`enfermeira` (
  `numero_registro` INT NOT NULL,
  `cre` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `enfermeira_chefe_numero_registro` INT NOT NULL,
  PRIMARY KEY (`numero_registro`),
  INDEX `fk_enfermeira_enfermeira_chefe1_idx` (`enfermeira_chefe_numero_registro` ASC) VISIBLE,
  CONSTRAINT `fk_enfermeira_enfermeira_chefe1`
    FOREIGN KEY (`enfermeira_chefe_numero_registro`)
    REFERENCES `mydb`.`enfermeira_chefe` (`numero_registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ala` (
  `id_ala` INT NOT NULL,
  `hospital_cnpj` VARCHAR(45) NOT NULL,
  `enfermeira_numero_registro` INT NOT NULL,
  PRIMARY KEY (`id_ala`),
  INDEX `fk_ala_hospital_idx` (`hospital_cnpj` ASC) VISIBLE,
  INDEX `fk_ala_enfermeira1_idx` (`enfermeira_numero_registro` ASC) VISIBLE,
  CONSTRAINT `fk_ala_hospital`
    FOREIGN KEY (`hospital_cnpj`)
    REFERENCES `mydb`.`hospital` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ala_enfermeira1`
    FOREIGN KEY (`enfermeira_numero_registro`)
    REFERENCES `mydb`.`enfermeira` (`numero_registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`enfermeira_chefe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`enfermeira_chefe` (
  `numero_registro` INT NOT NULL,
  PRIMARY KEY (`numero_registro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plano` (
  `tipo` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `telefone_operadora` VARCHAR(45) NULL,
  `nome_operadora` VARCHAR(45) NOT NULL,
  `hospital_cnpj` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nome_operadora`),
  INDEX `fk_plano_hospital1_idx` (`hospital_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_plano_hospital1`
    FOREIGN KEY (`hospital_cnpj`)
    REFERENCES `mydb`.`hospital` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medico` (
  `numero_registro` INT NOT NULL,
  `crm` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `especialidade` VARCHAR(45) NULL,
  `plano_nome_operadora` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`numero_registro`),
  INDEX `fk_medico_plano1_idx` (`plano_nome_operadora` ASC) VISIBLE,
  CONSTRAINT `fk_medico_plano1`
    FOREIGN KEY (`plano_nome_operadora`)
    REFERENCES `mydb`.`plano` (`nome_operadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paciente` (
  `idpaciente` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idpaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registro_atendimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`registro_atendimentos` (
  `paciente_idpaciente` INT NOT NULL,
  `medico_numero_registro` INT NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `hora` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`paciente_idpaciente`, `medico_numero_registro`, `data`, `hora`),
  INDEX `fk_paciente_has_medico_medico1_idx` (`medico_numero_registro` ASC) VISIBLE,
  INDEX `fk_paciente_has_medico_paciente1_idx` (`paciente_idpaciente` ASC) VISIBLE,
  CONSTRAINT `fk_paciente_has_medico_paciente1`
    FOREIGN KEY (`paciente_idpaciente`)
    REFERENCES `mydb`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_has_medico_medico1`
    FOREIGN KEY (`medico_numero_registro`)
    REFERENCES `mydb`.`medico` (`numero_registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
